
package vistaGUI;

/**
 *
 * @author estadm
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaDeEstatusCuenta
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListaClienteMenu = new javax.swing.JButton();
        btnRegistrarClienteMenu = new javax.swing.JButton();
        btnDepositarMenu = new javax.swing.JButton();
        btnTransferenciaMenu = new javax.swing.JButton();
        btnListaCuentaMenu = new javax.swing.JButton();
        btnConsultaTipoCambioCompraMenu = new javax.swing.JButton();
        btnRetirarMenu = new javax.swing.JButton();
        btnCambiarPinMenu = new javax.swing.JButton();
        btnConsultaSaldoActualMenu = new javax.swing.JButton();
        btnConsultaEstadoCuentaMenu = new javax.swing.JButton();
        btnConsultaEstatusCuentaMenu = new javax.swing.JButton();
        btnConsultaGananciasTotalizadoMenu = new javax.swing.JButton();
        btnConsultaGananciasindividualCuentaMenu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnRegistrarCuentaMenu = new javax.swing.JButton();
        btnConsultaTipoCambioVentaMenu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnConsultarGananciasComisionPorCadaCuenta = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");

        btnListaClienteMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnListaClienteMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaClienteMenu.setText("Listar clientes");
        btnListaClienteMenu.setBorder(null);

        btnRegistrarClienteMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnRegistrarClienteMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarClienteMenu.setText("Registrar cliente");
        btnRegistrarClienteMenu.setBorder(null);

        btnDepositarMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnDepositarMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDepositarMenu.setText("Depositar");
        btnDepositarMenu.setBorder(null);

        btnTransferenciaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnTransferenciaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransferenciaMenu.setText("Transferencia");
        btnTransferenciaMenu.setBorder(null);

        btnListaCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnListaCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaCuentaMenu.setText("Listar cuentas");
        btnListaCuentaMenu.setBorder(null);

        btnConsultaTipoCambioCompraMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaTipoCambioCompraMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaTipoCambioCompraMenu.setText("Consultar tipo cambio de compra");
        btnConsultaTipoCambioCompraMenu.setBorder(null);

        btnRetirarMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnRetirarMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRetirarMenu.setText("Retirar");
        btnRetirarMenu.setBorder(null);

        btnCambiarPinMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnCambiarPinMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCambiarPinMenu.setText("Cambiar pin");
        btnCambiarPinMenu.setBorder(null);

        btnConsultaSaldoActualMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaSaldoActualMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaSaldoActualMenu.setText("Consultar saldo actual");
        btnConsultaSaldoActualMenu.setBorder(null);

        btnConsultaEstadoCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaEstadoCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaEstadoCuentaMenu.setText("Consultar estado de cuenta");
        btnConsultaEstadoCuentaMenu.setBorder(null);

        btnConsultaEstatusCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaEstatusCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaEstatusCuentaMenu.setText("Consultar estatus de cuenta");
        btnConsultaEstatusCuentaMenu.setBorder(null);

        btnConsultaGananciasTotalizadoMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaGananciasTotalizadoMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaGananciasTotalizadoMenu.setText("Consultar ganancias por concepto de comisión totalizado");
        btnConsultaGananciasTotalizadoMenu.setBorder(null);

        btnConsultaGananciasindividualCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaGananciasindividualCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaGananciasindividualCuentaMenu.setText("Consultar ganancias por concepto de comisión ");
        btnConsultaGananciasindividualCuentaMenu.setBorder(null);
        btnConsultaGananciasindividualCuentaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaGananciasindividualCuentaMenuActionPerformed(evt);
            }
        });

        btnRegistrarCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnRegistrarCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarCuentaMenu.setText("Registrar cuenta");
        btnRegistrarCuentaMenu.setBorder(null);

        btnConsultaTipoCambioVentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaTipoCambioVentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaTipoCambioVentaMenu.setText("Consultar tipo cambio de venta");
        btnConsultaTipoCambioVentaMenu.setBorder(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen2.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen3.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen5.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen19.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen9.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen10.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen11.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen12.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen16.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen17.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen21.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen15.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen13.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen23.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen25.png"))); // NOI18N

        btnConsultarGananciasComisionPorCadaCuenta.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultarGananciasComisionPorCadaCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarGananciasComisionPorCadaCuenta.setText("Consultar ganancias por concepto");
        btnConsultarGananciasComisionPorCadaCuenta.setToolTipText("");
        btnConsultarGananciasComisionPorCadaCuenta.setBorder(null);
        btnConsultarGananciasComisionPorCadaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarGananciasComisionPorCadaCuentaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("de comisión en cada cuenta");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("totalizado en cada cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(817, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListaClienteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel12)))
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel14))
                                    .addComponent(btnRegistrarClienteMenu))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDepositarMenu))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(btnTransferenciaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnListaCuentaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRegistrarCuentaMenu)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel15))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel13)))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRetirarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCambiarPinMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnConsultaSaldoActualMenu)
                                        .addGap(114, 114, 114)
                                        .addComponent(btnConsultaEstadoCuentaMenu)
                                        .addGap(78, 78, 78)
                                        .addComponent(btnConsultaEstatusCuentaMenu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel5)
                                        .addGap(218, 218, 218)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(40, 40, 40))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultaTipoCambioCompraMenu)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultaTipoCambioVentaMenu)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel8)
                                .addGap(77, 77, 77)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarGananciasComisionPorCadaCuenta)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(20, 20, 20)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultaGananciasTotalizadoMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultaGananciasindividualCuentaMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addGap(84, 84, 84)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarClienteMenu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnListaClienteMenu)
                                .addComponent(btnTransferenciaMenu)
                                .addComponent(btnDepositarMenu)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListaCuentaMenu)
                            .addComponent(btnCambiarPinMenu)
                            .addComponent(btnRetirarMenu)
                            .addComponent(btnRegistrarCuentaMenu))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultaEstadoCuentaMenu)
                            .addComponent(btnConsultaSaldoActualMenu)
                            .addComponent(btnConsultaEstatusCuentaMenu)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultaTipoCambioCompraMenu)
                        .addComponent(btnConsultaTipoCambioVentaMenu))
                    .addComponent(btnConsultarGananciasComisionPorCadaCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultaGananciasTotalizadoMenu)
                    .addComponent(btnConsultaGananciasindividualCuentaMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarGananciasComisionPorCadaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarGananciasComisionPorCadaCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarGananciasComisionPorCadaCuentaActionPerformed

    private void btnConsultaGananciasindividualCuentaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaGananciasindividualCuentaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaGananciasindividualCuentaMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarPinMenu;
    public javax.swing.JButton btnConsultaEstadoCuentaMenu;
    public javax.swing.JButton btnConsultaEstatusCuentaMenu;
    public javax.swing.JButton btnConsultaGananciasTotalizadoMenu;
    public javax.swing.JButton btnConsultaGananciasindividualCuentaMenu;
    public javax.swing.JButton btnConsultaSaldoActualMenu;
    public javax.swing.JButton btnConsultaTipoCambioCompraMenu;
    public javax.swing.JButton btnConsultaTipoCambioVentaMenu;
    public javax.swing.JButton btnConsultarGananciasComisionPorCadaCuenta;
    public javax.swing.JButton btnDepositarMenu;
    public javax.swing.JButton btnListaClienteMenu;
    public javax.swing.JButton btnListaCuentaMenu;
    public javax.swing.JButton btnRegistrarClienteMenu;
    public javax.swing.JButton btnRegistrarCuentaMenu;
    public javax.swing.JButton btnRetirarMenu;
    public javax.swing.JButton btnTransferenciaMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
