/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGUI;

import java.awt.Font;
import java.awt.Label;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author estadm
 */
public class MenuPrincipal extends javax.swing.JFrame {
    //private javax.swing.JLabel jLabel3;
    /**
     * Creates new form CambiarPinPrimeraEtapa
     */
    public MenuPrincipal() {
        initComponents();
        /*
        jLabel3 = new javax.swing.JLabel();
        Label lblTitulo = new Label();
        lblTitulo.setLocation(15,15);
        
        JLabel jLabel1 = new javax.swing.JLabel();
        
        ImageIcon imagenFondo = new ImageIcon("/imagenes/Imagen2.png");
        jLabel3.setIcon(imagenFondo);
        jLabel3.setText( "Etiqueta1" );
        jLabel3.setFont( new Font( "Helvetica", Font.BOLD, 18 ) );
        jLabel3.setLocation(5, 5);
        add(jLabel3);*/
        //panel.getChildren().add(lblTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        btnRegistrarClienteMenu = new javax.swing.JButton();
        btnRegistrarCuentaMenu = new javax.swing.JButton();
        btnListaCuentaMenu = new javax.swing.JButton();
        btnCambiarPinMenu = new javax.swing.JButton();
        btnDepositarMenu = new javax.swing.JButton();
        btnRetirarMenu = new javax.swing.JButton();
        btnTransferenciaMenu = new javax.swing.JButton();
        btnConsultaTipoCambioCompraMenu = new javax.swing.JButton();
        btnConsultaTipoCambioVentaMenu = new javax.swing.JButton();
        btnConsultaSaldoActualMenu = new javax.swing.JButton();
        btnConsultaEstadoCuentaMenu = new javax.swing.JButton();
        btnConsultaEstatusCuentaMenu = new javax.swing.JButton();
        btnConsultaGananciasTotalizadoMenu = new javax.swing.JButton();
        btnConsultaGananciasindividualCuentaMenu = new javax.swing.JButton();
        btnListaClienteMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnRegistrarClienteMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnRegistrarClienteMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarClienteMenu.setText("Registrar cliente");
        btnRegistrarClienteMenu.setBorder(null);

        btnRegistrarCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnRegistrarCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarCuentaMenu.setText("Registrar cuenta");
        btnRegistrarCuentaMenu.setBorder(null);

        btnListaCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnListaCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaCuentaMenu.setText("Listar cuentas");
        btnListaCuentaMenu.setBorder(null);

        btnCambiarPinMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnCambiarPinMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCambiarPinMenu.setText("Cambiar pin");
        btnCambiarPinMenu.setBorder(null);

        btnDepositarMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnDepositarMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDepositarMenu.setText("Depositar");
        btnDepositarMenu.setBorder(null);

        btnRetirarMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnRetirarMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRetirarMenu.setText("Retirar");
        btnRetirarMenu.setBorder(null);

        btnTransferenciaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnTransferenciaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTransferenciaMenu.setText("Transferencia");
        btnTransferenciaMenu.setBorder(null);

        btnConsultaTipoCambioCompraMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaTipoCambioCompraMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaTipoCambioCompraMenu.setText("Consultar tipo cambio de compra");
        btnConsultaTipoCambioCompraMenu.setBorder(null);

        btnConsultaTipoCambioVentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaTipoCambioVentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaTipoCambioVentaMenu.setText("Consultar tipo cambio de venta");
        btnConsultaTipoCambioVentaMenu.setBorder(null);

        btnConsultaSaldoActualMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaSaldoActualMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaSaldoActualMenu.setText("Consultar saldo actual");
        btnConsultaSaldoActualMenu.setBorder(null);

        btnConsultaEstadoCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaEstadoCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaEstadoCuentaMenu.setText("Consultar estado de cuenta");
        btnConsultaEstadoCuentaMenu.setBorder(null);

        btnConsultaEstatusCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaEstatusCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaEstatusCuentaMenu.setText("Consultar estatus de cuenta");
        btnConsultaEstatusCuentaMenu.setBorder(null);

        btnConsultaGananciasTotalizadoMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaGananciasTotalizadoMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaGananciasTotalizadoMenu.setText("Consultar ganancias por concepto de comisión totalizado");
        btnConsultaGananciasTotalizadoMenu.setBorder(null);

        btnConsultaGananciasindividualCuentaMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnConsultaGananciasindividualCuentaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultaGananciasindividualCuentaMenu.setText("Consultar ganancias por concepto de comisión en cada cuenta");
        btnConsultaGananciasindividualCuentaMenu.setBorder(null);

        btnListaClienteMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnListaClienteMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaClienteMenu.setText("Listar clientes");
        btnListaClienteMenu.setBorder(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen3.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen5.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen19.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen9.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen10.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen11.png"))); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen12.png"))); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen13.png"))); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen15.png"))); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen16.png"))); // NOI18N

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen17.png"))); // NOI18N

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen21.png"))); // NOI18N

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen23.png"))); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen25.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultaTipoCambioCompraMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnConsultaTipoCambioVentaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(226, 226, 226))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(btnConsultaGananciasTotalizadoMenu)
                        .addGap(12, 12, 12)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultaGananciasindividualCuentaMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel15)
                        .addGap(172, 172, 172)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaCuentaMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2)))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))
                            .addComponent(btnRegistrarCuentaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarClienteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btnConsultaSaldoActualMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListaClienteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(jLabel12)
                                    .addGap(123, 123, 123)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(jLabel3)
                                            .addGap(108, 108, 108)
                                            .addComponent(jLabel5)
                                            .addGap(97, 97, 97)
                                            .addComponent(jLabel7))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(187, 187, 187)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnDepositarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(53, 53, 53)
                                                    .addComponent(btnTransferenciaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnRetirarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(21, 21, 21)
                                                            .addComponent(jLabel6)))
                                                    .addGap(54, 54, 54)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnCambiarPinMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(16, 16, 16)
                                                            .addComponent(jLabel8)))))))
                                    .addGap(10, 10, 10)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultaEstadoCuentaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnConsultaEstatusCuentaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListaClienteMenu))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jLabel7))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDepositarMenu)
                                    .addComponent(btnTransferenciaMenu)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarClienteMenu)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListaCuentaMenu)
                    .addComponent(btnRegistrarCuentaMenu)
                    .addComponent(btnRetirarMenu)
                    .addComponent(btnCambiarPinMenu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultaEstatusCuentaMenu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultaEstadoCuentaMenu)
                            .addComponent(btnConsultaSaldoActualMenu))
                        .addGap(12, 12, 12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultaTipoCambioVentaMenu)
                            .addComponent(btnConsultaTipoCambioCompraMenu))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultaGananciasindividualCuentaMenu)
                            .addComponent(btnConsultaGananciasTotalizadoMenu)))
                    .addComponent(jLabel9))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarPinMenu;
    public javax.swing.JButton btnConsultaEstadoCuentaMenu;
    public javax.swing.JButton btnConsultaEstatusCuentaMenu;
    public javax.swing.JButton btnConsultaGananciasTotalizadoMenu;
    public javax.swing.JButton btnConsultaGananciasindividualCuentaMenu;
    public javax.swing.JButton btnConsultaSaldoActualMenu;
    public javax.swing.JButton btnConsultaTipoCambioCompraMenu;
    public javax.swing.JButton btnConsultaTipoCambioVentaMenu;
    public javax.swing.JButton btnDepositarMenu;
    public javax.swing.JButton btnListaClienteMenu;
    public javax.swing.JButton btnListaCuentaMenu;
    public javax.swing.JButton btnRegistrarClienteMenu;
    public javax.swing.JButton btnRegistrarCuentaMenu;
    public javax.swing.JButton btnRetirarMenu;
    public javax.swing.JButton btnTransferenciaMenu;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
